import type { Metadata } from "next";
import { Montserrat, Quicksand, Zilla_Slab, Roboto } from "next/font/google";
import LenisProvider from "@/components/LenisProvider/LenisProvider";
import "./globals.css";

import Header from "@/components/layout/Header";
import Footer from "@/components/layout/Footer";

const montserrat = Montserrat({
  variable: "--montserrat",
  subsets: ["latin"],
});
const quicksand = Quicksand({
  variable: "--quicksand",
  subsets: ["latin"],
})
const zilla = Zilla_Slab({
  variable: "--zilla",
  subsets: ["latin"],
  weight: ['300','400','500','600','700'],
})
const roboto = Roboto({
  variable: "--roboto",
  subsets: ["latin"]
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${montserrat.variable} ${zilla.variable} ${quicksand.variable} ${roboto.variable}`}>
      <body className="antialiased montserrat">
        <LenisProvider />
        <Header />
          {children}
        <Footer />
      </body>
    </html>
  );
}
